# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            I'm Tiger
tagline:          'Sounds like a born to be wild style designer'
description:      'One day I found that it was more exciting to share my thoughts and acheivements by writting a blog rather than telling them to my girlfriend'
url:              http://tiger-ll.github.io

author:           
  name:           'Tiger'
  url:            https://twitter.com/Ger_Ti
  email: 		  tigersidea@gmail.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/tiger-ll
